portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
    
]

web/urls.py
""""URL patterns for web"""

from os import stat
from django.urls import path

# For image uploads
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'web'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Projects page
    path('projects/', views.projects, name='projects'),
    # About me page
    path('about-me/', views.about_me, name='about_me'),
    # Contact page
    path('contact/', views.contact, name='contact'),

    # In progress
    path('success/', views.success, name='success'),
    # Single project page
    path('projects/<str:prj_name>/', views.project, name='project')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

web/models.py
from portfolio.settings import MEDIA_ROOT
from django.db import models

# Create your models here.
class Project(models.Model):
    """Model to represent a project."""
    name = models.CharField(max_length=200)
    desc = models.TextField()
    # Will include images and other juicy stuff : >
    cover = models.ImageField(upload_to='images')

    def __str__(self):
        return self.name

web/forms.py
from django import forms

class ContactForm(forms.Form):
    # from_email = forms.EmailField(label='', widget=forms.TextInput(attrs={
    #     'placeholder': 'your.email@mail.com',
    #     'class': 'form-title',
    #     'cols': 40,
    # }))
    subject = forms.CharField(label='', widget=forms.TextInput(attrs={
        'placeholder': 'Subject',
        'class': 'form-title',
        'cols': 40,
    }))
    message = forms.CharField(label='', widget=forms.Textarea(attrs={
        'placeholder': 'Your message',
        'class': 'form-text',
        'cols': 80,
    }))
    

web/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

from .models import Project
from .forms import ContactForm
from portfolio.settings import RECEPIENT_EMAIL, DEFAULT_FROM_EMAIL

# Create your views here.
def index(request):
    """Displays the home page."""
    return render(request, 'web/index.html')

def projects(request):
    """Makes a query to the database and takes all the
    projects from there, passes them as context."""
    projects = Project.objects.all()
    context = {'projects': projects}
    return render(request, 'web/projects.html', context)

def project(request, prj_name: str):
    """Renders a single project page with detailed info
    and complete focus on this project."""

    # makes the project name better looking in the url 
    # Alien Invasion -> alien-invasion
    # def pretify_url():
    #     return prj_name.lower().replace(' ', '-')

    project = Project.objects.get(name=prj_name)
    context = {'project': project}
    return render(request, 'web/project.html', context)
    
def about_me(request):
    """About me page."""
    return render(request, 'web/about_me.html')

def contact(request):
    """Page containing the contact form plus a bit of info."""
    # SMTP server still not set up
    # https://learndjango.com/tutorials/django-email-contact-form

    #  Slight change, trying out new way of sending the email, doesn't work
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            # from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                # Most likely, smtp server problem
                # When fail_silently is set to false, It gives authentication error
                
                # FINALLY WORKED
                # The problem was with google and the 'less secure apps', short: even tho i provide the correct
                # details for logging in, the setting blocks me from sending the email. Enabling it made it work

                # Last step - Design and refining some stuff
                # also, i might change my work email and overall degoogle myself

                # SMTP on protonmail is a no no ;d
                send_mail(subject, message, DEFAULT_FROM_EMAIL, [RECEPIENT_EMAIL], fail_silently=False)
            except BadHeaderError:
                return HttpResponseRedirect('Invalid header found.')
            # Only for test purposes
            # In the future i will make my own logger
            print('Email Sent!')
            return redirect('web:success')
    return render(request, 'web/contact.html', {'form': form})

def success(request):
    return render(request, 'web/success.html')

web/templates/web/about_me.html
{% extends 'web/base.html' %}

{% block header %}
    <h1>About me</h1>
    <h3>Everything you need to know about this humble developer.</h3>
{% endblock %}

{% block content %}
    <p>I write code : )</p>
    <p>beep beep boo... *poof* </p>
    <p><a href="https://blog-val.herokuapp.com/" target="_blank">A WEBSITE!</a></p>

    <h2>Valentin Mirchev</h2>
    <a href="https://github.com/val-h" target="_blank">
        <img class="circle-image" src="https://avatars1.githubusercontent.com/u/59520085?s=460&u=e0fcff626aa348e4ce29441a19eba8e4e2bd1511&v=4" alt="">
    </a>
{% endblock %}

web/templates/web/base.html
<!DOCTYPE html>
<html lang='en'>
    <head>
        <title>Portfolio</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'web/style.css' %}">
    </head>
    <body>
        <div class="header-wrapper">
            <!-- will include a paralax image slide -->
            <header>
                <a href="{% url 'web:index' %}">
                    <img src="{% static 'web/images/logo_cropped.png' %}" alt="Logo">
                </a>
            </header>

            <nav>
                <a href="{% url 'web:index' %}">Home</a>
                <a href="{% url 'web:projects' %}">Projects</a>
                <a href="{% url 'web:about_me' %}">About me</a>
                <a href="{% url 'web:contact' %}">Contact</a>
            </nav>
        </div>

        <main>
            <div class="content-header">
                {% block header %}{% endblock %}
            </div>
            <div class="content">
                {% block content %}{% endblock %}
            </div>
        </main>

        <footer>
            <div class="footer-wrapper">
                <div class="footer-links">
                    <p>Social Media Links</p>
                </div>
                <div class="sitemap">
                    <p>Sitemap</p>
                </div>
                <div class="footer-info">
                    <p>Short info</p>
                </div>
            </div>

            <div class="credentials">
                © Valentin Mirchev 2020
            </div>
        </footer>
    </body>
</html>

web/templates/web/contact.html
{% extends 'web/base.html' %}

{% block header %}
    <h1>Contact</h1>
    <h3>Here is a short description of me and a contact form.</h3>
{% endblock%}

{% block content %}
    <p>Hire this web developer</p>

    <h3>Contact me:</h3>
    <form action="{% url 'web:contact' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="form-button" type="submit">Send</button>
    </form>
{% endblock%}

web/templates/web/index.html
{% extends 'web/base.html' %}

{% block header %}
    <h1>Portfolio website</h1>
    <h3>Made by <a href="https://github.com/val-h" target="_blank">Valentin Mirchev</a></h3>
{% endblock %}

{% block content %}
    <p>This is a sample paragraph</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim 
        veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex 
        ea commodo consequat. Duis aute irure dolor in reprehenderit in 
        voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur 
        sint occaecat cupidatat non proident, sunt in culpa qui officia 
        deserunt mollit anim id est laborum.</p>
{% endblock %}

web/templates/web/project.html
{% extends 'web/base.html' %}

{% block header %}
    <h1>{{ project.name }}</h1>
    <h3>{{ project.desc }}</h3>
{% endblock header %}

{% block content %}

    {% if project.cover %}
        <img src="{{ project.cover.url }}" alt="{{ project.name }}">
    {% endif %}
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim 
        veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex 
        ea commodo consequat. Duis aute irure dolor in reprehenderit in 
        voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur 
        sint occaecat cupidatat non proident, sunt in culpa qui officia 
        deserunt mollit anim id est laborum.</p>
    <!-- Description, pictures and link for livedemo. -->
{% endblock content %}

web/templates/web/projects.html
{% extends 'web/base.html' %}

{% block header %}
    <h1>My Projects</h1>
    <h3>Created with passion!</h3>
{% endblock %}

{% block content %}
    <!-- Sample projects build -->
    <div>
        {% for project in projects %}
        <!-- fookin worked! -->
        <!-- Well the grid layout didnt work-->
            <div class="grid-container">
                <a href="{% url 'web:project' project.name %}">
                    <h2 class="grid-title">{{ project.name }}</h2>
                </a>
                <p class="grid-desc">{{ project.desc }}</p>
                <!-- Image problems : | -->
                <!-- FIXED!, somewhat : D -->
                <img src="{{ project.cover.url }}" alt="{{ project.cover.url }}" class="grid-image">
            </div>
        {% empty %}
            <h2>Too bad, so sad! No projects : (</h2>
        {% endfor %}
    </div>
{% endblock %}

web/templates/web/success.html
{% extends 'web/base.html' %}

{% block header %}
    <h1>SUCCESS!</h1>
{% endblock %}

{% block content %}
    <p>Thank you for contacting me. I'll respond as soon as possible.</p>
    <a href="{% url 'web:index' %}">Home</a>
    <br>
    <a href="{% url 'web:contact' %}">Contact</a>
{% endblock %}